version: "3.8"
services:
  client-side:
    container_name: client-side
    image: client-side:latest
    ports:
      - 80:80
    networks:
      - app-network
    depends_on:
      - zuul-gateway
      - course-micro

  zuul-gateway:
    container_name: gateway-micro
    image: gateway-micro:latest
    ports:
      - 8765:8765
    depends_on:
      - eureka
    networks:
      - app-network

  eureka:
    container_name: eureka-micro
    image: springcloud/eureka
    networks:
      - app-network
    ports:
      - 8761:8761

  auth-micro:
    container_name: auth-micro
    image: auth-micro:latest
    ports:
      - 8080:8080
    networks:
      - app-network
    depends_on:
      - zuul-gateway
      - eureka
  
  course-micro:
    container_name: course-micro
    image: course-image:latest
    restart: always
    networks:
      - app-network
    ports:
      - 8001:8001
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://course-micro-mysql:3306/micro_course?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=course-db
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    depends_on:
      - course-micro-mysql
      - eureka
      - zuul-gateway

  course-micro-mysql:
    container_name: course-micro-mysql
    image: mysql:latest
    networks:
      - app-network
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=micro_course
      - MYSQL_USER=course-db
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password

networks:
    app-network:
      driver: bridge
  

